### ISSUE TITLE
在antd pro 4的项目中无法应用成功啊！

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-aliyun-theme#16]
如题，能否提供个详细点的、可用的说明？

**Comment by fengnex** [comment]
`import aliyunTheme from '@ant-design/aliyun-theme';

// config.js or .umirc.js
export default {
  "theme": aliyunTheme,
}`
这样不行

**Comment by afc163** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/76956510-24442500-694f-11ea-937e-62769439238f.png">

我测试是生效的。

**Comment by afc163** [comment]
https://github.com/afc163/antd-pro-aliyun-theme

**Comment by fengnex** [comment]
是不是项目语言必须用ts？js不行？

**Comment by fengnex** [comment]
@afc163 
你上传的这个确实可以，但是这个的theme就UI效果而言，和pro默认的太像了，不仔细看都看不出差别来。我之前看到的aliyun的theme是以绿色调为主的，刚刚找了好一会没找到。从这个角度而言，这个theme没有实现真正的aliyun的theme啊！

**Comment by fengnex** [comment]
pro生成的config/config.js文档中，theme的设置代码是下面这样的，ant-design-aliyun-theme的文档也是说按下面这样修改：
theme: {
    // ...darkTheme,
    "theme": aliyunTheme,
},

实际上必须按@afc163你上传的项目的写法写成下面这样才行：
theme: aliyunTheme,

还是觉得aliyunTheme的UI效果太像pro默认你的了，有理由相信这个theme在视觉效果上没有真正实现！

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-aliyun-theme#umi

文档没写错的，仔细看看。

**Comment by fengnex** [comment]
确实，抱歉！
