### ISSUE TITLE
在ts语言的pro版本下，无法使用aliyun-theme

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-aliyun-theme#18]
重现步骤：
1、修改config/config.ts，添加下面的语句：
import aliyunTheme from '@ant-design/aliyun-theme';
2、在config/config.ts中define前面增加一下这行：
theme: aliyunTheme,
3、执行yarn、yarn start，出现下面的错误：
yarn start
yarn run v1.22.0
$ umi dev
Cannot find module '@ant-design/aliyun-theme'
Require stack:
- D:\inspect\monitorcraft-front\config\config.ts
- D:\inspect\monitorcraft-front\node_modules\@umijs\core\lib\Config\Config.js
- D:\inspect\monitorcraft-front\node_modules\@umijs\core\lib\index.js
- D:\inspect\monitorcraft-front\node_modules\umi\lib\ServiceWithBuiltIn.js
- D:\inspect\monitorcraft-front\node_modules\umi\lib\forkedDev.js
Error: Cannot find module '@ant-design/aliyun-theme'
Require stack:
- D:\inspect\monitorcraft-front\config\config.ts
- D:\inspect\monitorcraft-front\node_modules\@umijs\core\lib\Config\Config.js
- D:\inspect\monitorcraft-front\node_modules\@umijs\core\lib\index.js
......

**Comment by afc163** [comment]
`yarn add @ant-design/aliyun-theme`

**Comment by fengnex** [comment]
要先执行yarn add @ant-design/aliyun-theme

还有，由于antd、pro都在升级，建议这个也保持开发，别长期停滞
