### ISSUE TITLE
请问这个主题，是不开发了吗？

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-aliyun-theme#26]

**Comment by afc163** [comment]
有什么需求么？

**Comment by leshalv** [comment]
想使用这套主题，但是发现长久没有更新了，有几个组件也没有对接，上个版本发布也是一年前了，文档上提示实验性，所以，不确定稳不稳定，来问下。

**Comment by afc163** [comment]
没更新主要是因为没人提需求，欢迎 PR。

> 我们不在阿里云的业务里，所以没人提需求。

**Comment by afc163** [comment]
已经在更新了：https://github.com/ant-design/ant-design-aliyun-theme/pull/34
