### ISSUE TITLE
button组件type为danger时样式错误

### ISSUE THREAD

**Issue by luchx** [ant-design/ant-design-aliyun-theme#6]
在引入阿里云主题样式下使用button按钮
```js
<Button type="danger">按钮</Button>
```
当按钮处于hover/active状态下，此时生效的样式分别为

![image](https://user-images.githubusercontent.com/17548394/64503969-2a05e180-d300-11e9-8882-6f8ef39ba777.png)

![image](https://user-images.githubusercontent.com/17548394/64503995-3b4eee00-d300-11e9-96cf-28aa9620c2d1.png)

这个很容易让人误以为是禁用状态，如下在Modal.confirm按钮会自动聚焦
```js
Modal.confirm({
    title: 'Are you sure delete this task?',
    content: 'Some descriptions',
    okText: 'Yes',
    okType: 'danger',
    cancelText: 'No',
    onOk() {
      console.log('OK');
    },
    onCancel() {
      console.log('Cancel');
    },
  });
```
![image](https://user-images.githubusercontent.com/17548394/64504279-6be35780-d301-11e9-9b5d-bde7041ba946.png)

**Comment by liujiayii** [comment]
![QQ截图20190919143722](https://user-images.githubusercontent.com/38902744/65219387-0d7d5c80-daeb-11e9-843e-7f92e6c926a3.png)
![QQ截图20190919143830](https://user-images.githubusercontent.com/38902744/65219458-2e45b200-daeb-11e9-9916-c74a1096e977.png)
我这感觉还挺正常的

**Comment by afc163** [comment]
请升级到最新版本的 antd。
